### ISSUE TITLE
Change line height and indents

### ISSUE THREAD

**Issue by frabyn** [frabyn/nodoc#2]
Line height in body text and headings should be a uniform 28pt--"double spaced"

All new paragraphs should be indented. Currently the first paragraph is not indented.

(Line height in tables, signature lines, and cover page need not change)

**Comment by frabyn** [comment]
Right now I am rendering a trial filing document and it is single spaced. Can you make it as here: line height in body text and headings should be 28pt, with the first line of each paragraph indented (but not headings).

Thank you!

**Comment by AndreyBPopov** [comment]
Hi Franklin! Could you please provide more details what I must to do? I have synced the repository now and don't see any new files after my commit which was 19 days ago. But I expect to see a trial filing document you are making now, don't I?

**Comment by AndreyBPopov** [comment]
In general, it was nothing to fix. Please just use \mainmatter command before main text to switch line spacing.
