### ISSUE TITLE
Create file defining addresses

### ISSUE THREAD

**Issue by frabyn** [frabyn/nodoc#31]
Right now, addresses are defined for a person like this:

\SetupPerson{JS}{%
appellant,
firstparty,
name={John Smith, Jr.},
address={French Robertson Unit\\4304 Highway 202, Beeville, TX 78102},
}

The "address" is most commonly going to be one of several prison units. I would like to create a file of all units abbreviated by name. Let's call it addresses.tex

So the program can accept something like

Right now, addresses are defined for a person like this:

\SetupPerson{JS}{%
appellant,
firstparty,
name={John Smith, Jr.},
address={\address[Robertson]},
}

Don't worry about filling in the addresses, just set it up and I'll fill in the data. Thanks.

**Comment by AndreyBPopov** [comment]
Completed.
