### ISSUE TITLE
In single issue cases, omit the issue number

### ISSUE THREAD

**Issue by frabyn** [frabyn/nodoc#33]
In cases when there is only one issue used, when printing the issue name in the header and table of contents, omit the number.

Currently:

`\issue{The record does not reflect that the visiting\\judge was legally qualified to handle this case}
`

Results in

```
ISSUE 1: The record does not reflect that the visiting
judge was legally qualified to handle this case

```
And instead should say just 

```
ISSUE: The record does not reflect that the visiting
judge was legally qualified to handle this case

```

But the current behavior should continue if two or more issues are used.

**Comment by AndreyBPopov** [comment]
Completed.
