### ISSUE TITLE
Only print Table of Authorities sections if authorities are defined under that section

### ISSUE THREAD

**Issue by frabyn** [frabyn/nodoc#35]
Right now, the table of authorities prints headings for types of authorities even if the brief does not contain that kind of authority.

For example, in a case the does not define a statute or a rule, the following headings print without anything below:

![screenshot from 2016-10-16 23-25-47](https://cloud.githubusercontent.com/assets/8341207/19425426/e9030fd6-93f7-11e6-9935-a38d6514056e.png)

The document should not print headings in the table of authorities unless that kind of authority is defined.

**Comment by AndreyBPopov** [comment]
Completed.
