### ISSUE TITLE
Add person tag "client" and add to document

### ISSUE THREAD

**Issue by frabyn** [frabyn/nodoc#37]
Right now the person can be defined in several ways, including here "appellant" and "firstparty"

```
\SetupPerson{JS}{%
appellant,
firstparty,
name={Jason Smith.},
address={French Robertson Unit\\4304 Highway 202\\Beeville, Texas 78102},
}
```

Add a field "client" and then print the person defined as the client's name in the "Conclusion and Prayer" section where the name is manually written now.

**Comment by AndreyBPopov** [comment]
Completed.
