### ISSUE TITLE
Replace lawdoc.cls with court-paper.cls

### ISSUE THREAD

**Issue by frabyn** [frabyn/nodoc#39]
texas-appellate-brief.cls was renamed court-paper.cls and now lives in the /appellate directory

In the trial directory, trial-filing relies on its own class file, lawdoc.cls, that mostly defines heading styles and pulls information about the lawyer and the client.

I prefer that trial-filing do the following:
1. Handle citations in the way defined in court-paper.cls
2. Pull client, case, and lawyer data from the files defined in court-paper.cls
3. allow for optional table of contents and table of citations

To do this, court-paper.cls should probably be moved.

Headings should be handled differently in trial-filing.tex than they are in court-paper.cls. (See other issue)

**Comment by AndreyBPopov** [comment]
Completed.
