### ISSUE TITLE
Configure formatting for trial-filing.tex

### ISSUE THREAD

**Issue by frabyn** [frabyn/nodoc#40]
Trial-filing should have very similar formatting court-paper.cls (14pt font, 28pt line height, Century Schoolbook font). The biggest difference will be that trial-filing will not use "Issue" headers.

The headers for trial-filing should be

```
1. Level 1
1.1 Level 2
1.1.1 Level 3
1.1.1.1 Level 4

```

**Comment by AndreyBPopov** [comment]
Completed.
