### ISSUE TITLE
Uniformly structure case data and update documents

### ISSUE THREAD

**Issue by frabyn** [frabyn/nodoc#42]
Expand the data kept about cases to reflect the full life cycle of cases.

Right now we collect the following data about cases, assuming the case begins as an appeal.

```
\docket{14-16-00138-CR}
\SelectCourt{TXcoa14}
\SelectTrialCourt{TXTrial}
\casebelow{1234567}
```

Expand and rename the data to reflect that the project now will generate documents for the entire lifecycle of a matter, starting in a trial court and going up.

So

```
TrialCourt
TrialCourtCaseNumber

AppellateCourt
ApellateCourtCaseNumber

WritCourt
WritCourtCaseNumber

WritAppealCourt
WritAppealCaseNumber
```

We no longer need to define "case below" in the data. The data will have all the case numbers, and the TeX document will call the correct one.

**Comment by AndreyBPopov** [comment]
Completed.
