### ISSUE TITLE
Let TeXLive to find class and style files in latex folder

### ISSUE THREAD

**Issue by AndreyBPopov** [frabyn/nodoc#43]
Hi Franklin,

I have completed issues #39, #40 and #42. Now all latest cls, sty and tex files in the 'appellate' directory. Please note that 'latex' folder contains the old version of court-paper.cls so don't use it --- the right version in 'appellate' folder.
What was done:
1. I moved macros responding for data handling in a separate package named 'lawdata.sty' which loaded internally by court-paper.cls;
2. Required formatting for trial filing is now in court-paper.cls --- just pass to court-paper the option 'trialfiling' i.e. \documentclass[14pt,trialfiling]{court-paper}

The main problem for now is that initially you have two copies of court-paper.cls: one in 'appellate' folder and the other in 'latex' folder.  If you wish that TeXLive was able to find court-paper.cls in 'latex' folder you must add this folder to TEXMFLOCAL tree using instruction from this post
[http://tex.stackexchange.com/questions/20160/how-to-register-my-own-packages-or-classes-in-a-separate-drive-to-tex-live-insta](http://tex.stackexchange.com/questions/20160/how-to-register-my-own-packages-or-classes-in-a-separate-drive-to-tex-live-insta)

Then you should move all cls and sty files from 'appellate' folder to 'latex' folder and texlive must find them during a compilation.
--
Regards,
Andrey

**Comment by frabyn** [comment]
Hi Andrey! I know that TeX will look one directory up, like this

`\documentclass[14pt,\documentclassflag]{../court-paper}
`

I'd prefer to put class files in the root of the repository and reference them from each directory rather than changing environment variables. Is that possible?

**Comment by AndreyBPopov** [comment]
Completed. Now all style files are in styles\tex\latex\nodoc\. Please don't forget add this folder to local texmf tree.

**Comment by frabyn** [comment]
Sorry, I've changed my mind. Now I want the calls to the class file to be internal to the nodoc directory. I am having too many problems with the environment variables. We can keep the standardized directory structure the same, as long as it is referenced locally rather than being found through the global environment variable.

**Comment by AndreyBPopov** [comment]
Completed.
