### ISSUE TITLE
Add additional style of trial filing

### ISSUE THREAD

**Issue by frabyn** [frabyn/nodoc#45]
In commit 4a7be00 extra words like "In the" and "No." were removed from the trial filing heading.

Now, the format for a trial filing is:

```
<trial cause no>

<party>     | <court name>
            |
v.          | <court place>
            |
<party>     |
```

For now, we will call this a "State Court Trial Filing"

Please add a "Federal Court Trial Filing" style in the following format:

```
<court name- in small caps>
<court place- in small caps>

<party>     | <trial cause no>
            |
v.          | <extra information>
            |
<party>     |
```

Extra information is a new field that can be defined in the trial data file.

**Comment by AndreyBPopov** [comment]
Do this issue not needed to be implemented?

**Comment by frabyn** [comment]
I did it myself! Landed in 99d2d11

**Comment by AndreyBPopov** [comment]
I have looked. You did this issue in the right way!

**Comment by AndreyBPopov** [comment]
Needs to be fixed according to new data fields scheme.

**Comment by AndreyBPopov** [comment]
To what stage the "Extra information" related is? e.g. trial, Appellate, Collateral Attack, ...

**Comment by frabyn** [comment]
Trial only

**Comment by AndreyBPopov** [comment]
Completed.
